python train.py \
  --model_config config/model_config_small.json \
  --tokenized_data_path data/tokenized/ \
  --tokenizer_path cache/vocab_small.txt \
  --raw_data_path data/train.json \
  --epochs 20 \
  --log_step 150 \
  --stride 512 \
  --output_dir model/ \
  --device 1,2,3 \
  --num_pieces 100 \
  --raw
